### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gabrjc** [m4nffd/weibull_count_model#1]
Hello, 
i really appreciate this work, thanks a lot.
i tried myself to implement the same algorithm but it's shit compared to yours.
The only problem is that sometimes the weibull_likelihood return a negative number and so , the logarithm became NaN .
How can i fix it? 
A dumb solution i adopted was to just to assign a negative log_l for example -10 but i thinks it's not the best way to proceed.
If you wanna help me I'll be grateful to you.
Thanks for all
gabrjc

**Comment by m4nffd** [comment]
Hi @gabrjc, a likelihood (by definition) is never smaller than 0, so that is what needs to be fixed. Can you share the parameters (y1, y2, l1, l2, c1, c2) for which you get a negative likelihood?

**Comment by gabrjc** [comment]
Hello, that's are the params:

WL= -0.002984937794280884
y1= 2 y2= 1 l1= 1.1363185079404927 l2= -0.01648042241476555

C1 = 1.050 C2 = 0.9831
I merged two dataset together and the away team is just get promoted from another league and i think that's the problem... do you know a smart fix?

**Comment by m4nffd** [comment]
The problem is that the likelihood gets negative, and there are two reasons behind that: first, l1 and l2 are positively defined, so they should never be < 0 as it was in your case—that's because I forgot an exponential, which I have added with my latest push. 

You can still get negative likelihood sometimes due to the fact that I am approximating the infinite sum that defines the Weibull likelihood (cf. Eq. (1) of https://blogs.salford.ac.uk/business-school/wp-content/uploads/sites/7/2016/09/paper.pdf). 
To avoid that I have multiplied the coefficient initialisation by 0.1, which helps to constrain the value of l1 and l2, so that this is less likely to happen
